import type { ConvictionResponse } from '~/types/conviction'

const kxsDetail = {
  ticker: 'KXS.TO',
  businessType: 'saas / compounder',
  bq: 14,
  tax: -2,
  conviction: 12,
  fsClass: 'strong' as const,
  fdDirection: 'positive' as const,
  yieldTrap: false,
  dimensions: [
    { name: 'Revenue quality', score: 2, source: 'auto' },
    { name: 'Growth trajectory', score: 2, source: 'auto+man' },
    { name: 'Margin quality (Rule of 40: 72)', score: 2, source: 'auto' },
    { name: 'Balance sheet', score: 1, source: 'auto' },
    { name: 'ROIC / WACC spread', score: 2, source: 'auto' },
    { name: 'Gross margin trend', score: 1, source: 'auto' },
    { name: 'Debt maturity risk', score: 0, source: 'auto' },
    { name: 'CEO quality (Wadsworth)', score: 2, source: 'manual' },
    { name: 'Capital allocation', score: 1, source: 'manual' },
    { name: 'Competitive moat', score: 2, source: 'manual' },
    { name: 'Macro tailwind (tariff)', score: 2, source: 'manual' },
    { name: 'Divergence signal', score: 0, source: 'auto' },
    { name: 'Deal delay risk', score: -1, source: 'manual' },
    { name: 'Insider ownership', score: 1, source: 'manual' },
    { name: 'Reinvestment runway', score: -1, source: 'manual' },
  ],
  oey: 5.8,
  oeyFloorLabel: 'SaaS floor ≥5%',
  pe: 48,
  pePercentile: 62,
  fdVotes: [
    { label: 'Revenue: growing (+22%)', direction: 'positive' as const },
    { label: 'Margins: expanding', direction: 'positive' as const },
    { label: 'FCF: improving', direction: 'positive' as const },
    { label: 'EPS revisions: upgrades', direction: 'positive' as const },
    { label: 'Buybacks: steady', direction: 'stable' as const },
  ],
  fdSummary: 'Revenue +22%, margins expanding, FCF improving, EPS upgrades',
  taxNote: 'EV/rev 6.2x → tier 2 (-2). SaaS floor 4x. PE at 62nd pctile — no extra penalty.',
  verdictNote: 'Outstanding business at a fair price. Full 100% allocation.',
}

const nvdaDetail = {
  ticker: 'NVDA',
  businessType: 'saas (high-beta)',
  bq: 11,
  tax: -5,
  conviction: 6,
  fsClass: 'strong' as const,
  fdDirection: 'positive' as const,
  yieldTrap: false,
  dimensions: [
    { name: 'Revenue quality', score: 2, source: 'auto' },
    { name: 'Growth trajectory', score: 2, source: 'auto+man' },
    { name: 'Margin quality (Rule of 40: 95)', score: 2, source: 'auto' },
    { name: 'Balance sheet', score: 1, source: 'auto' },
    { name: 'ROIC / WACC spread', score: 2, source: 'auto' },
    { name: 'Gross margin trend', score: 1, source: 'auto' },
    { name: 'Debt maturity risk', score: 0, source: 'auto' },
    { name: 'CEO quality (Jensen Huang)', score: 2, source: 'manual' },
    { name: 'Capital allocation', score: 1, source: 'manual' },
    { name: 'Competitive moat (CUDA)', score: 2, source: 'manual' },
    { name: 'Macro tailwind (AI cycle)', score: 2, source: 'manual' },
    { name: 'Divergence signal', score: 0, source: 'auto' },
    { name: 'Deal delay risk', score: 0, source: 'manual' },
    { name: 'Insider ownership', score: -1, source: 'manual' },
    { name: 'Reinvestment runway', score: -1, source: 'manual' },
  ],
  oey: 3.1,
  oeyFloorLabel: 'SaaS floor ≥5%',
  pe: 42,
  pePercentile: 94,
  fdVotes: [
    { label: 'Revenue: accelerating', direction: 'positive' as const },
    { label: 'Margins: at all-time high', direction: 'positive' as const },
    { label: 'FCF: improving', direction: 'positive' as const },
    { label: 'EPS revisions: upgrades', direction: 'positive' as const },
    { label: 'Buybacks: steady', direction: 'stable' as const },
  ],
  fdSummary: 'Revenue accelerating, margins at all-time high, FCF improving, EPS upgrades',
  taxNote: 'EV/rev 23x → saas tier 4 max (-4). PE at 94th pctile → floor trigger (-1 extra). Total tax: -5.',
  verdictNote: 'Exceptional business but valuation demands tax. Tactical 75% (fd positive → 85%).',
}

const telusDetail = {
  ticker: 'T.TO',
  businessType: 'income / telecom',
  bq: -5,
  tax: -1,
  conviction: -6,
  fsClass: 'moderate_low' as const,
  fdDirection: 'negative' as const,
  yieldTrap: true,
  dimensions: [
    { name: 'Revenue quality', score: 1, source: 'auto' },
    { name: 'Growth trajectory', score: 0, source: 'auto' },
    { name: 'Dist. coverage (FCF/div: 0.87x)', score: -1, source: 'auto' },
    { name: 'Balance sheet (Altman Z 1.4)', score: -1, source: 'auto' },
    { name: 'ROIC / WACC spread (0% spread)', score: 0, source: 'auto' },
    { name: 'Gross margin trend', score: -1, source: 'auto' },
    { name: 'Debt maturity risk', score: 0, source: 'auto' },
    { name: 'CEO quality (new)', score: -1, source: 'manual' },
    { name: 'Capital allocation', score: -1, source: 'manual' },
    { name: 'Competitive moat', score: 0, source: 'manual' },
    { name: 'Macro tailwind (rate sensitive)', score: -1, source: 'manual' },
    { name: 'Divergence signal', score: 0, source: 'auto' },
    { name: 'Deal delay risk', score: 0, source: 'manual' },
    { name: 'Insider ownership', score: 0, source: 'manual' },
    { name: 'Reinvestment runway', score: 0, source: 'manual' },
  ],
  oey: 6.4,
  oeyFloorLabel: 'Income floor ≥3%',
  pe: 34,
  pePercentile: 82,
  fdVotes: [
    { label: 'Revenue: +3% (mature)', direction: 'stable' as const },
    { label: 'Margins: compressing', direction: 'negative' as const },
    { label: 'FCF: partially debt-funded', direction: 'negative' as const },
    { label: 'EPS revisions: cuts', direction: 'negative' as const },
    { label: 'Buybacks: suspended', direction: 'negative' as const },
  ],
  fdSummary: 'Revenue +3% (mature), margins compressing, FCF partially debt-funded, CEO transition',
  taxNote: 'EV/rev 2.5x below income floor (4x) → +1 relief. PE 82nd pctile → -2. Net: -1. YIELD TRAP: 7.3% > TSX 7% threshold.',
  verdictNote: 'Deteriorating income business. Yield trap cancels BUY hard gate. Review position if held.',
}

export function getMockConviction(): ConvictionResponse {
  return {
    asOf: '2026-05-17',
    storeLive: true,
    health: {
      breakdown: {
        max: { count: 2, pct: 18 },
        tactical: { count: 4, pct: 36 },
        reduced: { count: 3, pct: 27 },
        cancel: { count: 2, pct: 18 },
      },
      yieldTraps: 1,
      yieldTrapTickers: ['T.TO'],
      avgConviction: 4.2,
      avgRange: { min: -6, max: 12 },
      equityCount: 11,
      businessTypes: [
        { type: 'compounder', count: 4, color: '#27ae60' },
        { type: 'saas', count: 3, color: '#3498db' },
        { type: 'income', count: 2, color: '#e67e22' },
        { type: 'cyclical', count: 2, color: '#888888' },
      ],
    },
    signals: [
      {
        id: 'kxs',
        ticker: 'KXS.TO',
        direction: 'LONG',
        function: 'DeltaDrift M',
        signalDate: '2026-05-12',
        convictionScore: 12,
        verdict: 'MAX CONVICTION',
        sizeModifier: '100%',
        bqScore: 14,
        fsClass: 'strong',
        fdDirection: 'positive',
        yieldTrap: false,
        isEquity: true,
        detail: kxsDetail,
      },
      {
        id: 'nvda',
        ticker: 'NVDA',
        direction: 'LONG',
        function: 'TrendPulse D',
        signalDate: '2026-05-14',
        convictionScore: 6,
        verdict: 'TACTICAL',
        sizeModifier: '85%',
        bqScore: 11,
        fsClass: 'strong',
        fdDirection: 'positive',
        yieldTrap: false,
        isEquity: true,
        detail: nvdaDetail,
      },
      {
        id: 'csco',
        ticker: 'CSCO',
        direction: 'LONG',
        function: 'TrendPulse W',
        signalDate: '2026-05-15',
        convictionScore: 3,
        verdict: 'REDUCED',
        sizeModifier: '40%',
        bqScore: 5,
        fsClass: 'moderate',
        fdDirection: 'stable',
        yieldTrap: false,
        isEquity: true,
      },
      {
        id: 'telus',
        ticker: 'T.TO',
        direction: 'LONG',
        function: 'TrendPulse D',
        signalDate: '2026-05-15',
        convictionScore: -6,
        verdict: 'YIELD TRAP',
        sizeModifier: '0%',
        bqScore: -5,
        fsClass: 'moderate_low',
        fdDirection: 'negative',
        yieldTrap: true,
        isEquity: true,
        detail: telusDetail,
      },
      {
        id: 'spy',
        ticker: 'SPY',
        direction: 'LONG',
        function: 'TrendPulse W',
        signalDate: '2026-05-15',
        convictionScore: null,
        verdict: 'N/A (ETF)',
        sizeModifier: '—',
        bqScore: null,
        fsClass: null,
        fdDirection: null,
        yieldTrap: false,
        isEquity: false,
      },
    ],
    portfolio: [
      {
        ticker: 'KXS.TO',
        name: 'Kinaxis',
        businessType: 'compounder',
        mtm: '+18.4%',
        mtmPositive: true,
        convictionScore: 12,
        verdict: 'MAX CONVICTION',
        borderClass: 'hold',
        actionNote: 'Hold — conviction stable, fd positive',
        actionColor: '#27ae60',
      },
      {
        ticker: 'T.TO',
        name: 'TELUS',
        businessType: 'income',
        mtm: '-3.2%',
        mtmPositive: false,
        convictionScore: -6,
        verdict: 'YIELD TRAP',
        borderClass: 'review',
        actionNote: 'Review — yield trap active, consider exiting',
        actionColor: '#c0392b',
      },
      {
        ticker: 'NVDA',
        name: 'Nvidia',
        businessType: 'saas',
        mtm: '+7.1%',
        mtmPositive: true,
        convictionScore: 6,
        verdict: 'TACTICAL',
        borderClass: 'hold',
        actionNote: 'Hold — valuation tax heavy but BQ exceptional',
        actionColor: '#27ae60',
      },
    ],
    contradictions: [
      {
        id: 'c1',
        kind: 'warning',
        ticker: 'T.TO',
        body: 'TrendPulse Daily signals LONG but Conviction Engine says CANCEL + yield trap active. Fundamental deterioration (-6 conviction) overrides quant signal. Recommended action: do not enter; if already held, review exit.',
      },
      {
        id: 'c2',
        kind: 'info',
        ticker: 'NVDA',
        body: 'DeltaDrift Daily signals LONG, conviction +6 TACTICAL. Note: CAGR alpha is negative (-31.09%) vs buy-and-hold. Strategy CAGR +14.93% still meaningful. Proceed at 75% size, not full conviction. Monitor valuation tax — currently at floor trigger.',
      },
    ],
  }
}
